trigger:
- master

pr: none

variables:
  Major: 1
  Minor: 1
  DotNetSdkVersion: 3.0.100

stages:
  - stage: Test_Stage
    jobs:
      - job:
        steps:
          - script: |
              echo Test_Stage
              echo Major:$(Major)
              echo Minor:$(Minor)
              echo DotNetSdkVersion:$(DotNetSdkVersion)
          - task: DotNetCoreCLI@2
            displayName: 'Run all the Integration Tests in the repo and gather coverage data'
            continueOnError: false
            inputs:
              command: test
              arguments: '-maxcpucount:1 /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:UseSourceLink=true /p:Include="[BlazorState]*"'
              projects: '**/*.Integration.Tests/*.csproj'

          - task: reportgenerator@4
            displayName: 'Test coverage Report Generator'
            inputs:
              reports: '$(Build.SourcesDirectory)/Tests/**/coverage.cobertura.xml'
              targetdir: '$(Build.SourcesDirectory)/CodeCoverage'
              reporttypes: 'HtmlInline_AzurePipelines;Cobertura;Badges'
              historydir: '$(Build.SourcesDirectory)/CodeCoverage/History'
              assemblyfilters: '+BlazorState'

          - task: PublishCodeCoverageResults@1
            displayName: 'Publish code coverage'
            inputs:
              codeCoverageTool: Cobertura
              summaryFileLocation: '$(Build.SourcesDirectory)/CodeCoverage/Cobertura.xml'
              reportDirectory: '$(Build.SourcesDirectory)/CodeCoverage'

  - stage: Build_Stage
    variables:
      Patch: 0
      BuildCounterReset: "12312312432423saxxasdfadf" #$(Major).$(Minor).$(Patch)
      BuildCounter: $[counter(variables.BuildCounterReset, 0)]
      Version: '$(Major).$(Minor).$(Patch)-$(BuildCounter)+$(DotNetSdkVersion)'
    jobs:
      - job:
        steps:
          - script: |
              echo Build_Stage
              echo Major:$(Major)
              echo Minor:$(Minor)
              echo DotNetSdkVersion:$(DotNetSdkVersion)
              echo Patch:$(Patch)
              echo BuildCounter:$(BuildCounter)
              echo Version:$(Version)

          - task: DotNetCoreCLI@2
            displayName: Build BlazorState for Pre release
            inputs:
              command: build
              arguments: '-maxcpucount:1 -p:Version=$(Version)'
              projects: 'Source/BlazorState/BlazorState.csproj'

          - task: PublishBuildArtifacts@1
            displayName: Publish Nuget Artifact
            inputs:
              PathtoPublish: $(System.DefaultWorkingDirectory)/Source/BlazorState/bin/Packages
              ArtifactName: 'NugetPreRelease'
              publishLocation: Container

  - stage: Staging_Stage
    jobs:
      - job:
        steps:
          - script: echo Staging
          - task: DownloadPipelineArtifact@2
            inputs:
              artifactName: 'NugetPreRelease'
              buildType: current
              targetPath: '$(Pipeline.Workspace)/PipelineArtifacts/Nuget'

          - task: NuGetCommand@2
            displayName: 'Push NuGet to Azure Devops Nuget feed.'
            inputs:
              command: push
              packagesToPush: '$(Pipeline.Workspace)/PipelineArtifacts/Nuget/*.nupkg;!$(Pipeline.Workspace)/PipelineArtifacts/Nuget/*.symbols.nupkg'
              nuGetFeedType: internal
              publishVstsFeed: 'dfe61826-f0b9-46b3-a391-23626fc363f2'

  - stage: Production_Stage
    jobs:
      - deployment: 
        environment: Production
        variables:
          PatchCounterReset: "anythingdifferent to reset the thing xxx123122343399" #$(Major).$(Minor)
          Patch: $[counter(variables.PatchCounterReset, 0)]
          Version: '$(Major).$(Minor).$(Patch)+$(DotNetSdkVersion)'
        strategy:
          runOnce:
            deploy:
              steps:
              - script: |
                  echo Production_Stage
                  echo Major:$(Major)
                  echo Minor:$(Minor)
                  echo DotNetSdkVersion:$(DotNetSdkVersion)
                  echo Patch:$(Patch)
                  echo Version:$(Version)
                  
              - task: DotNetCoreCLI@2
                displayName: Build BlazorState release
                inputs:
                  command: build
                  arguments: '-maxcpucount:1 -p:Version=$(Version)'
                  projects: 'Source/BlazorState/BlazorState.csproj'

              - task: PublishBuildArtifacts@1
                displayName: Publish Nuget Artifact
                inputs:
                  PathtoPublish: $(System.DefaultWorkingDirectory)/Source/BlazorState/bin/Packages
                  ArtifactName: Nuget
                  publishLocation: Container

              - task: NuGetCommand@2
                displayName: 'Push NuGet to Nuget.org'
                inputs:
                  command: push
                  packagesToPush: '$(Pipeline.Workspace)/PipelineArtifacts/Nuget/*.nupkg;!$(Pipeline.Workspace)/PipelineArtifacts/Nuget/*.symbols.nupkg'
                  nuGetFeedType: external
                  publishFeedCredentials: Nuget.org

              - task: GitHubRelease@1
                displayName: 'GitHub release (create)'
                inputs:
                  gitHubConnection: 'TimeWarp Enterprises GitHub'
                  target: '$(Build.SourceVersion)'
                  tagSource: userSpecifiedTag
                  tag: '$(GitHubReleaseVersion)'
                  repositoryName: 'TimeWarpEngineering/blazor-state'
                  title: '$(GitHubReleaseVersion)'
                  releaseNotesSource: filePath
                  releaseNotesFilePath: 'Documentation/ReleaseNotes.md'
                  addChangeLog: true
                  changeLogCompareToRelease: 'lastFullRelease'
                  changeLogType: 'commitBased'